### ISSUE TITLE
Input for model in test.py

### ISSUE THREAD

**Issue by yarqian** [junjun-jiang/BaMBNet#3]
Many thanks for your work. I am confused about the input for model in test.py. It seems that the COC maps are not used as input for model in test.py. While  the COC maps ARE used as input for model in train.py. Is it used for ablation study or a wrong setting. Many thanks.

**Comment by junjun-jiang** [comment]
During the early training phase, the COC maps also required to be used as the inputs, and will be discarded after the network converges. As a consequence, the model does not require the COC maps during the test phase.

**Comment by pingjun18-li** [comment]
> Many thanks for your work. I am confused about the input for model in test.py. It seems that the COC maps are not used as input for model in test.py. While the COC maps ARE used as input for model in train.py. Is it used for ablation study or a wrong setting. Many thanks.

> Many thanks for your work. I am confused about the input for model in test.py. It seems that the COC maps are not used as input for model in test.py. While the COC maps ARE used as input for model in train.py. Is it used for ablation study or a wrong setting. Many thanks.

Excuse me, have you finished the first step and get accurate COC map? I have patched the Canon data to 512*512 as the project of DPDD datasets  (https://github.com/Abdullah-Abuolaim/defocus-deblurring-dual-pixel), and trained use the config of option/train/COC_Dataset_Train.yaml, but get a wrong resuts as issue 1.

if you succeed , can u share your experience?
