### ISSUE TITLE
How to update the thresholds r2, r3, r4 in your code?

### ISSUE THREAD

**Issue by FlyFish-space** [junjun-jiang/BaMBNet#5]
In Section III C of your paper, the thresholds r2-4 are updated by adaptively learning from a small amountof meta-data. However, I don't find this part in your code. I only find you give four  `static_kernel_size` . ”Combined with the model training process, generatingthe defocus mask is a nested optimization“ Where is the nested optimization?

**Comment by junjun-jiang** [comment]
The nest optimization is not based on a gradient-optimized way. In practice, we manually compute the updated values  in each iteration. As a result, we published the optimal values in the `static_kernel_size`.

**Comment by FlyFish-space** [comment]
ok，thanks！

**Comment by jucaizhai** [comment]
hello，I have a question like this ,too. the thresholds r2-4 updated values not use the hyperparameter search method ，while manually Grid search？

**Comment by junjun-jiang** [comment]
Please refer to the Sec.III.C in paper. 
For convenience, we provide the deblurring results of DPDBlur test dataset (https://drive.google.com/file/d/1xkRaaJbqH6R0Mv42Rea3nB4hkRmgodbj/view?usp=sharing).

**Comment by jucaizhai** [comment]
ok,thank you!
