### ISSUE TITLE
The input of model  in train.py and test.py

### ISSUE THREAD

**Issue by FlyFish-space** [junjun-jiang/BaMBNet#6]
1. In your code train.py, the model input is (l_img, r_img, b_img).  Is b_img COC map of train dataset? But b_img is not obtained in your blur_train.py. So do I need to change your code blur_test.py to obtain b_img?
2. In your code test.py, the model input is (l_img, r_img, r_img).If there’s been a mistake？Why do you concatnate two r_img?

**Comment by junjun-jiang** [comment]
During the testing phase, we do not need the COC images any more. The input of evaluation model is just used to reuse code.

**Comment by FlyFish-space** [comment]
Is b_img in the training code COC Map of training data?

**Comment by junjun-jiang** [comment]
Yeah. 
We used an annealing strategy during training. Therefore, the b_img is used for initial several epochs.
