### ISSUE TITLE
您好，想请问下代码的事情

### ISSUE THREAD

**Issue by TPZZZ** [junjun-jiang/BaMBNet#7]
您好，
如果我没有理解错误的话，在您的文章中，是用defocusmask将一张图图像分成4张图像分别进入预设好的sub-restorer,但是在您的模型包括训练和测试文件当中这个好像没有体现出来，不知道是我的理解错还是少看了文章的部分，能不能请您解答一下呢？

**Comment by erfect2020** [comment]
正如文章中的描述，我们仅仅在训练阶段使用defocus mask，在测试阶段不需要defocus mask.
在训练代码中，我们使用defocus map分割得到defocus mask.

**Comment by junjun-jiang** [comment]
正如文章中的描述，我们仅仅在训练阶段使用defocus mask，在测试阶段不需要defocus mask.
在训练代码中，我们使用defocus map (kernel_de_param_net.py:81L)分割得到defocus mask.

**Comment by TPZZZ** [comment]
您好，但是我在训练代码里面也没看见如您文章Fig.3 中，将defocus mask 与输入图像相乘之后输入不同的restorer的操作？
然后如果在测试阶段不适用defocus mask 怎么能将输入图像根据困难程度分成4类输出呢？
因为您文章的摘要上“Based on the assumption that different image regions
with different blur amounts have different deblurring difficulties,
we leverage different networks with different capacities (i.e.
parameters) to process different image regions” 写的就是要根据这个defocus maps然后处理不同困难程度的region的。

**Comment by junjun-jiang** [comment]
请阅读 kernel_de_param_net.py中L:139~144

**Comment by TPZZZ** [comment]
好的，谢谢指导~
